# Generated by Django 3.2.7 on 2021-10-18 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
        migrations.AlterField(
            model_name='user',
            name='vip_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
