# Generated by Django 3.2.7 on 2021-10-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_user_vip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0, max_length=11, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
    ]
