# Generated by Django 3.2.7 on 2021-09-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
                ('desc', models.TextField(default='add descriptions here.')),
                ('rate', models.CharField(choices=[('2', 'Good'), ('3', 'Very good'), ('1', 'Bad')], max_length=1)),
                ('auth', models.CharField(choices=[('Admins', (('A', 'Atid'), ('R', 'Rahmat'), ('N', 'Noora'))), ('Normal people', (('Y', 'Yasin'), ('E', 'Ebne')))], max_length=1)),
                ('img', models.ImageField(upload_to='foodPics/')),
                ('check', models.BooleanField(default=False, verbose_name='آیا اجازه انتشار می\u200cدهید؟')),
            ],
        ),
    ]
