# Generated by Django 3.2.7 on 2021-09-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210920_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodels',
            name='auth',
            field=models.CharField(choices=[('Admins', (('Atid', 'Atid'), ('Rahmat', 'Rahmat'), ('Noora', 'Noora'))), ('Normal people', (('Yasin', 'Yasin'), ('Ebne', 'Ebne')))], max_length=20),
        ),
    ]
