# Generated by Django 3.2.7 on 2021-09-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_foodmodels_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه\u200c ها',
            },
        ),
        migrations.AddField(
            model_name='foodmodels',
            name='categ',
            field=models.ManyToManyField(related_name='categs', to='food.Category'),
        ),
    ]
