# Generated by Django 3.2.7 on 2021-10-11 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0007_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodels',
            name='user',
            field=models.ManyToManyField(null=True, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
