# Generated by Django 3.2.7 on 2021-10-11 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0008_foodmodels_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmodels',
            name='user',
        ),
        migrations.AddField(
            model_name='foodmodels',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
