# Generated by Django 3.2.7 on 2021-10-18 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0009_auto_20211011_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodels',
            name='user',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
