# Generated by Django 3.2.7 on 2021-10-21 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0010_alter_foodmodels_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodels',
            name='special_article',
            field=models.BooleanField(default=False, verbose_name='مقاله\u200cی ویژه'),
        ),
        migrations.AlterField(
            model_name='foodmodels',
            name='user',
            field=models.ForeignKey(default='User.id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
